### PR TITLE
feat(Pivot): Pivot directive

### LINKED ISSUE #33: Component to create: pivot
Official link to component description & demo: http://dev.office.com/fabric/components/pivot

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

### PR DESCRIPTION
**Pull request by jjczopek**
This is a **work in progress PR** for Pivot component.

Component works in most cases as expected, but there are couple of things to notice:
- spacing between pivot items is not consistent (especially visible on tabs), even though the markup that is generated by the directive is no different from the Fabric UI demo markup,
- even though all of the test cases are executed and they pass testing various parts of the component, code coverage is only 40% for the component.

Documentation still to come.

I submit this PR to get feedback on whether functionality is as expected and to get input/feedback how to solve the issues mentioned above.

Closes #33.

### CODE REVIEW

**Comment by andrewconnell** [comment]
LGTM!

**Comment by andrewconnell** [comment]
I updated the comment in this PR to say "Closes # 33" (no space) to link this up to the issue in our Waffle board (Waffle looks for "Closes #000" in the text of the PR description to link the two up so when the PR is closed, it automatically closes the issue... hence why that exact text is in the PR template).

**Comment by jjczopek** [comment]
I pushed final version of pivot to my WIP branch. It has documentation and work around for the spacing issues. However the contextual menu that is in the ellipsis does not display properly now and coverage is still poor. 
Feel free to review.

**Comment by andrewconnell** [comment]
So… are you saying the “WIP” label doesn’t apply now and you’re ready for merge?

**Comment by jjczopek** [comment]
@andrewconnell : the demo isn't working as I would like it to work, but other than that it's good. If I'll not figure anything better, I'll squash it and remove WIP and then it will be ready for merge. But maybe someone by that time will figure out how to fix the demo :P

**Comment by jjczopek** [comment]
The issue with contextual menu not displaying properly was identified as bug in Fabric. Therefore I will submit make proper PR in the evening.

**Comment by andrewconnell** [comment]
OK… so I’m not clear if we can merge this as is now with some undesirables with Fabric’s CSS, or if we should wait?

I’m getting confused with open PRs that “aren’t ready” :) If a PR isn’t ready, all good to close it and reopen / resubmit a new one later.

**Comment by jjczopek** [comment]
As of now I consider it ready to be merged.

**Pull request closed without merging**
