### PR TITLE
WIP: #20 dialog

### LINKED ISSUE #20: Component to create: dialog
Official link to component description & demo: http://dev.office.com/fabric/components/dialog

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

### PR DESCRIPTION
**Pull request by jigargandhi**
WIP Do not merge

Closes #20.

### CODE REVIEW

**Comment by jigargandhi** [comment]
I see some problem in searchbox files while merging.. will resolve it and update the pull requests

**Comment by jigargandhi** [comment]
@ac need help here.. could you please remove `searchBoxDirective.*.ts` and run the build again.

**Comment by andrewconnell** [comment]
I don't follow... I can't remove a directive to get another one to build. I can see that your branch is behind `master` but only by one (and in your fork I see your `dev` branch is way behind... that's not important if you just didn't push your local updates to your fork). What seems to be the problem?

BTW you know you can hook up Travis to your fork so you can push and see if the build is good before submitting the PR? It's no big deal to submit the PR and let Travis pick it up here.

**Comment by ghost** [comment]
Just checking, @jigargandhi Have you had time to look at this?

**Comment by jigargandhi** [comment]
@rolandoldengarm, @andrewconnell   you can now merge the PR. @andrewconnell the issue was that components.ts had `searchBoxDirective` in the imports while the actual filename was `searchboxDirective` (Note the capitalization of B)

**Comment by andrewconnell** [comment]
This was very hard to get merged... now that it has been merged, can you please delete your fork and re-fork? I seem to be seeing the same things coming across in each PR. There were commits in this PR from December that had already been merged. The only thing I can think is that your dev branch is way out of sync...

You had committed the gulpfile.js to your repo... that should not be done as it's dynamically generated.

PRs should address a single issue and not include unrelated changes. This PR for the dialog included A LOT of changes to searchbox. That should not be done. If there are changes that need to happen to the searchbox, please file an issue and create a new commit.

In the future PRs like this will be rejected and the contributor will be expected to clean it up and fix things. Ultimately I took the `src/components/dialog` folder from your fork and added it to a new branch off `dev`, updated `src/core/components.ts` to include dialog and tested things which they all worked. I did one commit and set the author to you... but in the future this won't be done. 

If you need help with managing your git repo to fix issues, please feel free to reach out in the #general channel in Slack.

**Comment by jigargandhi** [comment]
As suggested by @andrewconnell , I have deleted my fork and re forked the repo. Hoping the same issues will not be repeated in the future.

**Pull request closed without merging**
