### PR TITLE
Fixes #381

### LINKED ISSUE #381: uifFacePile always displays overflow text
uifFacePile always displays overflow text even if limit is not exceeded. 

Example: uiOverFlowLimit is set to 5, and we have 3 people in the array. Then the overflow text is _+-2_.

_update: submitted PR with fix._

### PR DESCRIPTION
**Pull request by newq**

### CODE REVIEW

**Comment by andrewconnell** [comment]
Please fix the error in the build and resubmit this PR. Easy vetting fix...

**Comment by newq** [comment]
@andrewconnell which error did i miss here?

**Comment by andrewconnell** [comment]
Look at the PR… it failed the vetting when Circle CI processed it.

**Comment by andrewconnell** [comment]
Looks like closing the PR lost the Circle history. See this: https://circleci.com/gh/ngOfficeUIFabric/ng-officeuifabric/161

**Pull request closed without merging**
