### PR TITLE
New Panel Directive

### PR DESCRIPTION
**Pull request by ghost**
Closes issue #29

Code coverage 100%, vet passes

In addition, update to uifCommandBar to allow for the recalculation of the visible
items via broadcast i.e. in circumstances where the shown items are
required to be updated but a window.resize has not fired. This was required for the panel, as the uifCommandBar is hidden on load, therefore a 0 width - hiding all items.

### CODE REVIEW

**Comment by andrewconnell** [comment]
I can't seem to get the demo to work on this... I see references to `basic.html` & `withcommandbar.html` but those files aren't in the project. In addition, the panel directive is not being rendered. Also missing the reference to the panel directive in the `components.ts` file.

Can you please take a look at these and resolve these issues so I can see the working demo before merging?

**Comment by ghost** [comment]
basic.html and withcommandbar.html are include ng-include files, so I suspect the issue relates to the missing reference in components.ts. I'll take a look this evening

**Comment by andrewconnell** [comment]
Manually merged to `dev`

**Comment by ghost** [comment]
Hey @andrewconnell, did I do something wrong in the PR, or was it just easier for you to manually merge? Just asking for future ref :)

**Comment by andrewconnell** [comment]
I manually merge everything... we want to keep updates confined to a single commit for a cleaner commit log, plus I had to update the `changelog.md` with your changes.

**Comment by ghost** [comment]
OK cool :)

On Mon, Apr 18, 2016 at 3:42 AM -0700, "Andrew Connell" <notifications@github.com<mailto:notifications@github.com>> wrote:

I manually merge everything... we want to keep updates confined to a single commit for a cleaner commit log, plus I had to update the changelog.md with your changes.

##

**Pull request closed without merging**
