### PR TITLE
Update dependency on Angularjs to 1.6.10

### PR DESCRIPTION
**Pull request by Sjark**
Update angularjs dependency to 1.6.10, the newest version in the 1.6.x branch.

### CODE REVIEW

**Comment by Sjark** [comment]
Not sure why the circleci build fails. It works locally when using yarn install and yarn run build:ts, might be because the CI build uses npm?

**Comment by andrewconnell** [comment]
We're not going to switch the package manager out of the blue as NPM has worked just fine in the past.

That's coming from someone who prefers Yarn over NPM.

**Comment by andrewconnell** [comment]
The build details indicate there's an error in dependencies: https://circleci.com/gh/ngOfficeUIFabric/ng-officeuifabric/313

There haven't been any updates to this project in a VERY long time... the last real update was almost 18 months ago: https://github.com/ngOfficeUIFabric/ng-officeuifabric/graphs/code-frequency

The project has been in a "archive" or "maintenance" state since then as there's no new dev being added.

**Comment by Sjark** [comment]
I have no problem with that, only saw that there was no package-lock.json, only yarn.lock, so I bet that is the reason the build is failing. I'll have a look at getting the build working using npm.

**Comment by andrewconnell** [comment]
That's only because at the time, there was no locking capability in NPM. The fact it's there doesn't do anything unless Yarn is being used.

**Comment by Sjark** [comment]
Any thoughts on my latest commit? It builds fine now.

**Comment by andrewconnell** [comment]
Yeah sorry... I process PR's for a few repos at the same time and this just happened to get in the day after I do that... got a lot on my plate this week and also planning to do a few other changes to the docs on this repo at the same time when I do a push. Will get to it within the week. Sorry for the delay.

**Comment by andrewconnell** [comment]
Manually merged and rolling out as 0.16.10

**Pull request closed without merging**
