### PR TITLE
feat(orgchart): add new directive #27

### LINKED ISSUE #27: Component to create: orgchart
Official link to component description & demo: http://dev.office.com/fabric/components/orgchart

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

### PR DESCRIPTION
**Pull request by SteenMolberg**
Finally done. Hope everything is ok to merge.

Closes #27.

### CODE REVIEW

**Comment by andrewconnell** [comment]
Nice work! The demo runs (with a little attention from the list below) & looks great. However there are a few things that need to discuss & address before we can merge it in. 

In the demos I see how you can bind a collection of people. What if the developer doesn't have a collection of people but rather needs to write them out? Looking at the source I think that's doable, but could you add that to the demo? I think this references your [comment about making it easier to use](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/27#issuecomment-181015732). I think we are all for making it easy to use the directives... but other directives don't work that way (see `uif-table` where all rows & cells are written out).

This is a bit confusing to me too: I see different binding syntax within the attributes on the directive... some things appear to be bound to the control, others appear to be used by the child elements. Keeping track of which needs the `{{}}` and which doesn't could get confusing for the developer.

I see where the `uif-primary-text` & `uif-secondary-text` are set as attributes on the directive rather than elements. I take it that these are not used on the parent control, rather on the inner nested controls? If so, shouldn't these be elements (along with `uif-image` & `uif-presence`) and be on the actual persona and not on the org chart?

Other items that need attention:
- [ ]  JSDOC for directive needs updated "see" reference pointing to the Office UI Fabric component (see https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/icon/iconDirective.ts#L43 for reference) [#1636637077](https://www.wunderlist.com/#/tasks/1636637077)
- [ ]  Need a core JavaScript `../demo`... every directive needs a plain demo folder [#1636637082](https://www.wunderlist.com/#/tasks/1636637082)
- [ ]  Missing import in the `/src/core/components.ts`... without this directive doesn't run [#1636637085](https://www.wunderlist.com/#/tasks/1636637085)
- [ ] In the demo I see the use of a `uif-method` attribute that appears to let the developer run code when the item is selected (I think), but I don't see this documented in the directive's JSDOC. Building off this, I see in the `demoTypeScriptUsage` the attributes are all documented, but more importantly these docs need to be within the actual directive. In the future we will dynamically generate our docs and explanation of the public signature that developers can control should be where we can dynamically pull it out. 
  If I'm correct in understanding what this does, shouldn't specific events get bubbled up that the developer can manipulate? Seems like the way it's implemented now only allows for a **click** event... but what if I wanted to have different events happen when I hovered over, right-click, etc? Seems like those would not be possible?
- [ ]  Not sure what's causing this, but test suite runs three times every time I run it. The first two times only a subset of the tests are run (see below) [#1636637087](https://www.wunderlist.com/#/tasks/1636637087)
  image

**Comment by SteenMolberg** [comment]
Hi AC, 
and thxs for your comment. I don't if it is custom to continue discussion here or on the original task-thread but here it goes...
- About all the missing documentation. Sorry about that I must have forgotten in the hurry to get it done... got a little late as well:) I will take care of that and also see if I can figure out why test run multiple times.
- I have rewritten the directive more according to my [suggestion](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/27#issuecomment-181010936) to change and to what you are saying in your comment.

I looks like this now...

```
        <uif-org-chart uif-select-mode="single" uif-style="standard">
            <uif-org-chart-group ng-repeat="group in vm.items | uifOrgChartGroupBy: 'department'">
                <uif-org-chart-group-title>{{group}}</uif-org-chart-group-title>
                <uif-org-chart-list>
                    <uif-org-chart-persona ng-repeat="person in vm.items | filter: {'department': group}"
                                           uif-status="{{person.status}}"
                                           uif-item="person" ng-click="vm.ShowPerson(person)"
                                           uif-selected="{{person.selected}}">
                        <uif-org-chart-image ng-src="{{person.imageUrl}}"></uif-org-chart-image>
                        <uif-org-chart-presence></uif-org-chart-presence>
                        <uif-org-chart-details>
                            <uif-org-chart-primary-text>{{person.name}}</uif-org-chart-primary-text>
                            <uif-org-chart-secondary-text>{{person.title}}</uif-org-chart-secondary-text>
                        </uif-org-chart-details>
                    </uif-org-chart-persona>
                </uif-org-chart-list>
            </uif-org-chart-group>
        </uif-org-chart>
```
- I think this is more in line with the other directives and the user have more control. For example he can apply a click action to the person or however he likes it.
- I have tried to get rid of -list and -details directive but was not able to figure out how without getting rid of the flexibility as well
- About grouping: To my knowledge there's no standard group-by filter for ng-repeat in Angular so I have exposed the filter I used in the previous version so the user can use this or something else
- About selection: I have copied the way selection works on the table-directive, but I not agree with the way you get the selected items... from what I can see I creates a table property on the controllers scope, but what if I would like to have more than one table in my controller. Or have I misunderstood something? I much rather like the user to supply an array for the selected items... I have seen that approach else where.

**Comment by andrewconnell** [comment]
Cool… everything sounds & looks good! I don’t see an updated code push… have you updated your fork?

As for the table & selected item… I’m not sure I follow. Need to loop @waldekmastykarz in since he owns that…

**Comment by waldekmastykarz** [comment]
Hi @SteenMolberg, could you provide some more information about the issue that you are experiencing with how selected items are retrieved?

**Comment by SteenMolberg** [comment]
Hi @waldekmastykarz 
If you are using 2 table-directives within your controller they share the same table.collection on the controllers scope. 
For example: With 2 table-directives with the same controller. With one item selected in both you get an array of 2 items back when you call...
console.log($scope.table.selectedItems);

Or am I just doing it wrong?

On another note:
I suggested in the above that maybe we implement SelectedItems so that the developer would supply the array for selected items in an attribute like uif-selected-items="vm.selected". Like in this [project](https://github.com/jtrussell/angular-selection-model#selectionmodelselecteditems). What do you think about that?

**Comment by SteenMolberg** [comment]
Hi @andrewconnell 
No AC I did not. Just wanted your feedback before I did documentation stuff and so on.

**Comment by andrewconnell** [comment]
Gotcha… well the above looks good so feel fee to update it.

**Comment by waldekmastykarz** [comment]
@SteenMolberg do you have a working sample that we could have a look at together to get a better understanding of this issue? :smile: 

What would be the use case of providing a separate list of selected items rather than keeping track of which items are selected using their properties (eg. `item.selected = true`)?

**Comment by SteenMolberg** [comment]
HI @waldekmastykarz 

I have pushed a [demo ](https://github.com/SteenMolberg/ng-officeuifabric/blob/tabledemo/src/components/table/demo/index.html) to my own fork to show what I mean. I modified the index.html and index.js slightly.

At the bottom of the page I have inserted a second table-directive and a two buttons.

A problem is IMHO is that both table-directives use the same table-property on the scope. Resulting in two selected items in the log when you get the $scope.table.selectedItems on the Show selected-button. This is of course because the table does not use isolated scope. If it would use isolated scope I don't know any other way than for me to supply the array to the directive where I can get the selected items. There might be a more elegant way.

I think that using isSelected would be fine, but I think the directive should update the isSelected property on the item and then the developer can filter for the selected items. That that might be ok, but that would leave some work the developer, and then we are back to an array where he can easily get the selected items.

Really like to hear your opinion about this.

**Comment by waldekmastykarz** [comment]
@SteenMolberg I see. I wonder though: is selection the only problem or would we need to revisit the whole component. What if you had multiple tables within a controller and would like to programmatically change properties of one of them. Wouldn't you have the same problem?

**Comment by SteenMolberg** [comment]
Hi @waldekmastykarz 
Maybe we should schedule a time in slack or better on Skype to get to the bottom of this?

**Comment by waldekmastykarz** [comment]
@SteenMolberg good idea. How about we move this thread to Slack and involve others who could help as well?

**Comment by andrewconnell** [comment]
Closing this PR as it doesn't appear ready to merge. Please feel free to re-open later.

**Pull request closed without merging**
