### PR TITLE
fix(textfield): Disabled not watched

### PR DESCRIPTION
**Pull request by andikrueger**
The disabled attributed of uif-textfield was not watched, causing removing/adding the
attribute not to update the component.

Targets #268

### CODE REVIEW

**Comment by andrewconnell** [comment]
Thanks for the PR... can you resolve the build errors?

**Comment by andikrueger** [comment]
Working on it...

**Comment by andrewconnell** [comment]
You know you can run the automated build tests locally before submitting the PR?

https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/MPA.md#execute-all-unit-tests

**Comment by andikrueger** [comment]
Actually I did, but wasn't as successful as I planned to be. I'm glad there is #285 addressing some of my troubles about MPA and Tests documentation. I ran "gulp test" but missed the tslint one in the end. It's my first contribution to a git project. 

During testing I found a bug:
The class is-active got only handled if the text field was underlined. The current test didn't notice it, because it only checked for it to be not present. I addressed that as well.

**Comment by andrewconnell** [comment]
Merge conflicts when I tried to merge it. I tried to merge it but it still caused issues with failing tests. Can you please rebase on the `dev` branch and resolve these issues?

**Comment by andikrueger** [comment]
I'll have a look at it.

**Comment by andikrueger** [comment]
I experienced another issue with IE 10 and disabled. I opened a new issue at the Office UI Fabric [https://github.com/OfficeDev/Office-UI-Fabric/issues/500](https://github.com/OfficeDev/Office-UI-Fabric/issues/500). Should we fix that one as well or wait for their response?

**Comment by andrewconnell** [comment]
manually merged to `dev`

**Pull request closed without merging**
