### PR TITLE
feat: Textfield multiline and pass - Closes #227.

### LINKED ISSUE #227: TextField does not support multiline or change of input type
The uif-textfield directive should have multiline support, and also allow the specification of the type. (Eg. a password field)

### PR DESCRIPTION
**Pull request by florinszilagyi**
Closes Issue #227 

Added a new attribute (uif-multiline) for the uif-textfield directive to render the directive as a multi-line text area.

Added a new attribute (uif-type) for the uif-textfield directive to render the directive as a password input.

### CODE REVIEW

**Comment by ghost** [comment]
Hi thank you! It looks better than the previous PR, but there are still some things missing:
- New `uif-type` attribute added, yet no error checking ([guideline 007](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/DIRECTIVE-CHECKLIST.md#directive-attribute-validation))
- No demos added with new use cases... these must be added with descriptions

Could you please work on these?

**Comment by florinszilagyi** [comment]
Sure thing.
Is it alright if I leave it to default to "text" if it's not set?

**Comment by ghost** [comment]
Yes please, default = text. Thanks.

**Comment by andrewconnell** [comment]
Is this finished? It doesn't appear so... but confused as the title says it closes an issue...

**Comment by ghost** [comment]
It's not ready. I've raised two issues, you raised before, but are not solved yet.

**Comment by andrewconnell** [comment]
I'm going to close this until the PR is ready to be merged... open PR's make it seem like they are waiting to be merged and keeping track of what's ready is ripe for a mistake.

**Comment by ghost** [comment]
@florinszilagyi It would be a shame if it wouldn't be merged as you are almost there. Are you able to fix the last two issues and submit a new PR?

**Comment by florinszilagyi** [comment]
I'll try to make a new PR this week.

Thanks

**Pull request closed without merging**
