### PR TITLE
NavBar directive implementation.

### LINKED ISSUE #26: Component to create: navbar
Official link to component description & demo: http://dev.office.com/fabric/components/navbar

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

### PR DESCRIPTION
**Pull request by s-KaiNet**
Closes #26 
Contextual menu also adjusted a bit to support more graceful interaction with other directives.  
Note on changes in `config/build.ts` - 'ALL_SPEC_FILES'. NavBar requires contextual menu controller to perform some actions on contextual menu. When running tests karma first runs contextual menu tests and then nav bar tests. Also karma coverage tries to show coverage for all "requiring" files, for example when testing nav bar, `navbardirective.js` has good coverage, but uses a small subset of functionality from contextual menu. Coverage confused and shows low coverage for contextual menu. This can be demonstrated with following config: 

``` javascript
public static ALL_SPEC_FILES: string[] = [
    'src/components/contextualmenu/contextualMenu.js',
    'src/components/navbar/navbarDirective.js',
    'src/components/contextualmenu/contextualMenu.spec.js',
    'src/components/navbar/navbarDirective.spec.js'
];
```

generates following coverage: 

From the other side this config (consider order):  

``` javascript
public static ALL_SPEC_FILES: string[] = [
    'src/components/navbar/navbarDirective.js',
    'src/components/contextualmenu/contextualMenu.js',
    'src/components/contextualmenu/contextualMenu.spec.js',
    'src/components/navbar/navbarDirective.spec.js'
];
```

this time coverage are good: 

I don't know how to deal with that properly, so had to change the file inclusion order, may be needs some investigation lately.

### CODE REVIEW

**Comment by andrewconnell** [comment]
I'm not understanding why there are changes to the spec collection in the `build.ts` file that add non-spec files. That collection is only intended to include specs... nothing else. This change now makes it so it's spec files + navbar & command bar directive.

I'm just not understanding why this is necessary when no other directives require it. Can you explain more? Is there no other option because I _really_ don't want to go in this direction... because if it is required, we need to look at the root cause and how things are organized because `All_SPEC_FILES` is not longer "all spec files".

**Comment by s-KaiNet** [comment]
> That collection is only intended to include specs... nothing else    

I think you are not correct here. See how it in `dev` branch now: 

``` javascript
public static ALL_SPEC_FILES: string[] = [
    'src/components/*/!(*.spec).js',
    'src/components/*/*.spec.js'
];
```

`'src/components/*/!(*.spec).js'` - this includes all `*.js` files under components folder, exept `*.spec.js`, `'src/components/*/*.spec.js'` - includes all `*.spec.js` files. So `ALL_SPEC_FILES` includes both src and spec files. In this case files are included in alpha- order and it's equivalent to: 

``` javascript
public static ALL_SPEC_FILES: string[] = [
    //sources
    'src/components/button/buttonDirective.js'
    .....
    'src/components/contextualmenu/contextualMenu.js',
    'src/components/navbar/navbarDirective.js',
    .....
    //specs
    'src/components/button/buttonDirective.spec.js'
    .....
    'src/components/contextualmenu/contextualMenu.spec.js',
    'src/components/navbar/navbarDirective.spec.js'
    ......
    'src/components/toggle/toggleDirective.spec.js'
];
```

In this particular order coverage shows only 30% for contextual menu, because nav bar uses subset of contextual menu functionality and goes **after** contextual menu in source files inclusion (why it works so - I really don't know).  
To see the issue just checkout my branch and put original `ALL_SPEC_FILES`:  

``` javascript
public static ALL_SPEC_FILES: string[] = [
    'src/components/*/!(*.spec).js',
    'src/components/*/*.spec.js'
];
```

Run gulp test and see 30% coverage for contextual menu, which is not true. The only workaround I found is change the order of source file inclusion: 

``` javascript
  public static ALL_SPEC_FILES: string[] = [
    'src/components/*/!(*.spec|contextualMenu|navbarDirective).js',
    'src/components/navbar/navbarDirective.js',
    'src/components/contextualmenu/contextualMenu.js',
    'src/components/*/*.spec.js'
  ];
```

`'src/components/*/!(*.spec|contextualMenu|navbarDirective).js',` - all *.js except *.spec.js except contextualMenu.js except navbarDirective.js. Then navbar and contextual menu in particular order. In that case coverage for contextual menu correct

**Comment by s-KaiNet** [comment]
In some projects I saw they create one file with all required source, something like this one (`karma.scripts.js`): 

``` javascript
var context = require.context('./App', true, /-test\.ts?$/);
context.keys().forEach(context);
```

In this case I believe coverage should show correct data.

**Comment by andrewconnell** [comment]
Ah... I see what you're saying now. Man that's strange!

**Comment by s-KaiNet** [comment]
Just found that there is `uif-overlay` directive, but I'm using plain fabric html instead of our directive. Need to address it, so temporary add WIP title.

**Comment by s-KaiNet** [comment]
> Just found that there is uif-overlay directive, but I'm using plain fabric html instead of our directive. Need to address it, so temporary add WIP title.  

Implemented

**Pull request closed without merging**
