### PR TITLE
Feature: Searchbox directive

### PR DESCRIPTION
**Pull request by jigargandhi**
Adding following files for the search box feature
- searchboxdirective.ts
- searchboxdirective.test.ts

### CODE REVIEW

**Comment by andrewconnell** [comment]
Thanks for the submission... I'm still working on docs and getting the automated tests running, but until then, can you update your submission to include two things?
- [ ] rename your test file to `*.spec.ts`
- [ ] include example usage with the folder `demoBasicUsage` similar to how @rolandoldengarm did here: https://github.com/rolandoldengarm/ng-officeuifabric/tree/34d4f38bd7df35e1c09bbf3ddbdbd509d98aafe1/src/components/textfield

**Comment by andrewconnell** [comment]
Looks like you have some build errors... see the details of the build. It appears you have invalid path references to the type definitions in your spec file, but you don't even need those... you can remove them all together because the `tsconfig.json` file in the root configures TypeScript to build them. 

Please ensure your build passes before submitting the PR. Getting close! :smile:

**Comment by jigargandhi** [comment]
I see there is some problem with the uniqueids spec will fix it and recommit

**Comment by jigargandhi** [comment]
I do not know if this commit should be counted as valid ??

**Comment by ghost** [comment]
I also noticed you have jQuery dependencies. It shouldn't be too hard to remove that dependency. Easiest way is to use querySelector. 
Probably best / fastest is to use other techniques, like jqLite, or by not using javascript at all to bind events. In this case it's only used to attach events to HTML elements in the template, there are other, more angular ways of doing this.

**Comment by andrewconnell** [comment]
Also noticed the code coverage for the directive is pretty low (~60%) which brings the overall coverage number down to ~83%... while it might seem like the bar is set unreasonably high I think with multiple people contributing to an open source project, it's important we have good test coverage.

If you need help running the local jobs to see what the test coverage is and what lines are / are not being hit, ping me here. I'm going to write a doc up about it but in the mean time, happy to help.

**Comment by jigargandhi** [comment]
I agree with @rolandoldengarm regarding jQuery dependencies, I will remove it, add a controller for the operations and commit again,

@andrewconnell :I understand the purpose of high %age of code coverage, but I am not used to code coverage and might take a few more commits to get it done, Please bear with me :)

**Comment by andrewconnell** [comment]
No sweat... happy to help if you request it. Might try running the code coverage reports locally though and not having to wait for them to be reported here.

They are build automatically when you run the tests. When you run `gulp test` or `./node_modules/karma/bin/karma start ./build/karma.conf.js --single-run`, karma internally uses istanbul and creates a `/coverage` folder. Nested within that you'll see an HTML report which is the same thing that coveralls.io is reporting in your build check.

BTW, soon I plan to add TypeScript vetting to the travis build pipeline... so if you throw linting errors in your TypeScript, you'll have to address those before the PR is accepted & merged. You can run a local report using `gulp vet-lib-ts` to see what issues you have in your TypeScript.

**Comment by jigargandhi** [comment]
What should the expected coverage of code be?

**Comment by andrewconnell** [comment]
Ideally pretty high… we have it set to fail an automatic build if it isn’t above 90%

If you merge the latest changes from the dev branch you’ll get an update from issue #52 that will help as we were getting penalized for not testing the dynamically generated code for webpack. The new workflow uses the coverage for the the JS we generate, not the stuff webpack generates, which is more correct. IOW, files like core.ts & components.ts are now up to 100%

**Comment by andrewconnell** [comment]
Just pulled this down to run locally... looks good! I noticed two things you do need to address (one of which we aren't accounting for in the automatic Travis builds, but it will eventually cause a failing build):
- remove the `console.log()` statements from your tests... we should only see test results when you run `gulp test --specs`
- you have 90+ code style issues that you can see if you run `gulp vet` ... these are easy fixes to knock out (*this is the one that should get added to travis builds in the future)

Your code coverage looks pretty good (90%+).

Make sure you aren't committing the `gulpfile.js` ... that's dynamically built all the time.

However when I try to run the demo, I'm getting an errors loading the 'demoApp`module... one is pretty easy... you need to make sure you add the searchbox to the`src\core\components.ts` file. However I'm seeing two other errors showing up related to uniqueId's:

image

**Comment by jigargandhi** [comment]
Final touches to Searchbox directive commited
- Removed console.log from searchboxdirective.spec.ts
- Fixed gulp vet issues
- Removed gulpfile.js
- Resolved errors while running the demo

**Comment by andrewconnell** [comment]
:+1: awesome... I'll pull it down later today and run through things again, hopefully pushing it out to **dev**!

**Comment by andrewconnell** [comment]
I'm real sorry to do this, but I'm still having issues with the searchbox component when I try to merge it... we're close though! 

First, when I went to merge stuff, there were conflicts that needed to be resolved because your branch is not in sync with the main repo's **dev** branch. Because you'd been on this one for a while I was going to do this for you, but then ran into blocking issues below... so next time you submit, please make sure you resync your local **dev** branch from upstream & rebase your branch off the updated one. Check the [PULL-REQUESTS](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/PULL-REQUESTS.md) for info on resync'ing your repo from upstream to avoid merge conflicts.
- [ ] there's no documentation on the scope interface in your directive... see how the [ITextFieldScope](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/dev/src/components/textfield/textFieldDirective.ts#L5-L32) is documented for reference.
- [ ] one of your tests is failing: **should have unique ids**
- [ ] suggest that you include one of your demos to have a searchbox with no text prefilled, for instance, nothing set on the `uif-value` attribute... in fact...
- [ ] because there's already a valid `value` attribute, we really should be using that so we don't have a custom attribute defined?
- [x] to see changed is to have the attribute `uif-search` to be changed to `placeholder` following the same convention we are using in existing directives, specifically the [textfield](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/dev/src/components/textfield/demo/index.html#L65). This could have been caught had we had a spec in the original issue like the other directives we have... you just jumped on this one so quick which is awesome! :)

It's close... I know it seems like every time you submit something it's something different that's keeping it from getting added... really appreciate your commitment and effort here!

**Comment by jigargandhi** [comment]
@andrewconnell I am sorry, I did not understand the 4th point 

```
because there's already a valid value attribute, we really should be using that so we don't have a custom attribute defined?
```

Could you please elaborate on it?
Do you mean to say just use `ngModel` like you have done in TextField directive?

Unfortunately, I do not see the test **should have unique ids** failing on my machine. Anything, I may be missing ?

Thank you

**Comment by andrewconnell** [comment]
I'm referring to the `uif-value` attribute that the directive adds. There's already an attribute `value` so just use that to pass the value into the textbox to prefill it. We don't need to create our own implementation of the value attribute as the `value` attribute already does what you're doing with `uif-value`.

As for the tests... as for the tests, I don't know what to say... when I pull your PR down I am doing it on a clean branch that's been rebased off **dev** so it should be pretty clean. I can take another look when I merge some other PR's today and send you the details if it happens again.

**Comment by jigargandhi** [comment]
I am not sure why the `tsc -p ./` command fails in travis, works perfectly locally. @andrewconnell  please check

**Comment by andrewconnell** [comment]
Check the casing of the name. The filename is search**B**oxDirective.ts but you're referencing it with a lcase **b**. I'm guessing your developing on Windows where case doesn't matter... the build script runs on a Linux container where case matters.

**Comment by andrewconnell** [comment]
I just saw the issue with the failing test... check out the recent find by @rolandoldengarm about unique ID's... he ran into it with the `uif-toggle` directive and found a solution. He talked about it in the slack channel: https://ngofficeuifabric.slack.com/archives/general/p1452564827000297

**Comment by jigargandhi** [comment]
@andrewconnell I have fixed the unique id issue as per idea by @rolandoldengarm , please check and merge with the `master` if suitable

**Comment by andrewconnell** [comment]
Unfortunately this is not ready to get merged due to multiple issues that have [been raised previously](https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/8#issuecomment-169973921). 

I have checked the items off that i see you have addressed above... but you can see the ones that remain unchecked. I appreciate the work you've done, but **please resolve these before resubmitting**. 

I have cloned your own repo and run the tests and see them failing... this says to me that you are are not verifying tests pass before submitting the PR. You can run tests yourself & they should all pass before submitting a PR.

**I'm closing the PR for now and when you have these fixed, you are free to resubmit & reopen the PR**.

## outstanding issues
- [ ] [as mentioned previously](https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/8#issuecomment-169973921), failing test on [unique id's](https://github.com/jigargandhi/ng-officeuifabric/blob/feat-searchboxdirective/src/components/searchbox/searchboxDirective.spec.ts#L31)
  image
- [ ] [as mentioned previously](https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/8#issuecomment-169973921), we don't want to prefix attributes with 'uif-' that are not custom attributes... if it's an attribute that exists on the underlying HTML control that serves the same purpose. Specifically, this directive should not have [uif-value](https://github.com/jigargandhi/ng-officeuifabric/blob/feat-searchboxdirective/src/components/searchbox/searchboxDirective.ts#L25) rather that should simply be `value`
- [ ] the [jsdoc for the interface does not match the code](https://github.com/jigargandhi/ng-officeuifabric/blob/feat-searchboxdirective/src/components/searchbox/searchboxDirective.ts#L4-L26)... properties are listed that are not present & not all properties are documented
- [ ] when I ran the demo, i'm not seeing the placeholder text get set in the search control... this should work like other placeholders - default text that's lightly colored from real text & is cleared out once the inbox control onfocus & replaced onblur

**Pull request closed without merging**
