### PR TITLE
Fixed issues with angular 1.4.9

### PR DESCRIPTION
**Pull request by s-KaiNet**
Solves #139

### CODE REVIEW

**Comment by andrewconnell** [comment]
I'm still seeing the errors pop up on the demo page when I click one of the submenus... it triggers 20 of these when the menu opens.

**Comment by s-KaiNet** [comment]
Hmmm.. no errors for me.. Did you rebuild library in dev mode?  
If so can you please say which exact menus have errors when clicking?

**Comment by andrewconnell** [comment]
My bad... I'm not sure what I did yesterday... its working now. Very strange... merging now...

**Comment by andrewconnell** [comment]
Manually merged to branch `dev`

**Pull request closed without merging**
